variable "user_data_path" {}
variable "db_engine" {}
variable "engine_version" {}
variable "db_instance_class" {}
variable "db_identifier" {}
variable "db_name" {}
variable "db_username" {}
variable "db_password" {}
variable "db_skip_final_snapshot" {}
variable "db_backup_retention_period" {}
